// Generated from the externally maintained reference artwork and rig. DO NOT EDIT.
import Foundation

enum CharacterReferenceCatalog {
  static func rig(_ id: CharacterReferenceArtworkID) -> CharacterReferenceRig {
    switch id {
    case .mascotHero:
      return .init(id: id, width: 419, height: 339, layers: [
        .init(part: .body, asset: "reference-mascot-hero-body",
          pivotX: 209.5, pivotY: 169.5,
          frame: .init(x: 0, y: 0, width: 419, height: 339)),
        .init(part: .headsetShell, asset: "reference-mascot-hero-headset-shell",
          pivotX: 209.5, pivotY: 169.5,
          frame: .init(x: 0, y: 0, width: 419, height: 339)),
        .init(part: .headsetMetal, asset: "reference-mascot-hero-headset-metal",
          pivotX: 209.5, pivotY: 169.5,
          frame: .init(x: 0, y: 0, width: 419, height: 339)),
        .init(part: .headsetCushions, asset: "reference-mascot-hero-headset-cushions",
          pivotX: 209.5, pivotY: 169.5,
          frame: .init(x: 0, y: 0, width: 419, height: 339)),
        .init(part: .headsetLight, asset: "reference-mascot-hero-headset-light",
          pivotX: 209.5, pivotY: 169.5,
          frame: .init(x: 0, y: 0, width: 419, height: 339)),
        .init(part: .eyeLeft, asset: "reference-mascot-hero-eye-left",
          pivotX: 162.0, pivotY: 180.5,
          frame: .init(x: 140, y: 121, width: 44, height: 119)),
        .init(part: .eyeRight, asset: "reference-mascot-hero-eye-right",
          pivotX: 245.0, pivotY: 179.5,
          frame: .init(x: 223, y: 120, width: 44, height: 119)),
        .init(part: .mouth, asset: "reference-mascot-hero-mouth",
          pivotX: 203.5, pivotY: 232.5,
          frame: .init(x: 188, y: 222, width: 31, height: 21)),
      ])
    case .mascotWhite:
      return .init(id: id, width: 192, height: 175, layers: [
        .init(part: .body, asset: "reference-mascot-white-body",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetShell, asset: "reference-mascot-white-headset-shell",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetMetal, asset: "reference-mascot-white-headset-metal",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetCushions, asset: "reference-mascot-white-headset-cushions",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetLight, asset: "reference-mascot-white-headset-light",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .eyeLeft, asset: "reference-mascot-white-eye-left",
          pivotX: 75.5, pivotY: 92.0,
          frame: .init(x: 64, y: 63, width: 23, height: 58)),
        .init(part: .eyeRight, asset: "reference-mascot-white-eye-right",
          pivotX: 114.5, pivotY: 92.0,
          frame: .init(x: 103, y: 63, width: 23, height: 58)),
        .init(part: .mouth, asset: "reference-mascot-white-mouth",
          pivotX: 95.0, pivotY: 116.5,
          frame: .init(x: 87, y: 110, width: 16, height: 13)),
      ])
    case .mascotBlack:
      return .init(id: id, width: 192, height: 175, layers: [
        .init(part: .body, asset: "reference-mascot-black-body",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetShell, asset: "reference-mascot-black-headset-shell",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetMetal, asset: "reference-mascot-black-headset-metal",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetCushions, asset: "reference-mascot-black-headset-cushions",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .headsetLight, asset: "reference-mascot-black-headset-light",
          pivotX: 96.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 192, height: 175)),
        .init(part: .eyeLeft, asset: "reference-mascot-black-eye-left",
          pivotX: 75.0, pivotY: 92.0,
          frame: .init(x: 63, y: 63, width: 24, height: 58)),
        .init(part: .eyeRight, asset: "reference-mascot-black-eye-right",
          pivotX: 114.5, pivotY: 92.0,
          frame: .init(x: 103, y: 63, width: 23, height: 58)),
        .init(part: .mouth, asset: "reference-mascot-black-mouth",
          pivotX: 95.0, pivotY: 116.5,
          frame: .init(x: 86, y: 110, width: 18, height: 13)),
      ])
    case .mascotArcade:
      return .init(id: id, width: 198, height: 175, layers: [
        .init(part: .body, asset: "reference-mascot-arcade-body",
          pivotX: 99.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 198, height: 175)),
        .init(part: .headsetShell, asset: "reference-mascot-arcade-headset-shell",
          pivotX: 99.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 198, height: 175)),
        .init(part: .headsetMetal, asset: "reference-mascot-arcade-headset-metal",
          pivotX: 99.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 198, height: 175)),
        .init(part: .headsetCushions, asset: "reference-mascot-arcade-headset-cushions",
          pivotX: 99.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 198, height: 175)),
        .init(part: .headsetLight, asset: "reference-mascot-arcade-headset-light",
          pivotX: 99.0, pivotY: 87.5,
          frame: .init(x: 0, y: 0, width: 198, height: 175)),
        .init(part: .eyeLeft, asset: "reference-mascot-arcade-eye-left",
          pivotX: 73.0, pivotY: 92.5,
          frame: .init(x: 61, y: 64, width: 24, height: 57)),
        .init(part: .eyeRight, asset: "reference-mascot-arcade-eye-right",
          pivotX: 114.5, pivotY: 92.5,
          frame: .init(x: 103, y: 64, width: 23, height: 57)),
        .init(part: .mouth, asset: "reference-mascot-arcade-mouth",
          pivotX: 94.0, pivotY: 117.0,
          frame: .init(x: 85, y: 111, width: 18, height: 12)),
      ])
    case .mascotBare:
      return .init(id: id, width: 290, height: 289, layers: [
        .init(part: .body, asset: "reference-mascot-bare-body",
          pivotX: 145.0, pivotY: 144.5,
          frame: .init(x: 0, y: 0, width: 290, height: 289)),
        .init(part: .eyeLeft, asset: "reference-mascot-bare-eye-left",
          pivotX: 104.5, pivotY: 131.5,
          frame: .init(x: 84, y: 78, width: 41, height: 107)),
        .init(part: .eyeRight, asset: "reference-mascot-bare-eye-right",
          pivotX: 180.5, pivotY: 131.0,
          frame: .init(x: 160, y: 78, width: 41, height: 106)),
        .init(part: .mouth, asset: "reference-mascot-bare-mouth",
          pivotX: 142.5, pivotY: 178.0,
          frame: .init(x: 128, y: 169, width: 29, height: 18)),
      ])
    case .norwegianWarm:
      return .init(id: id, width: 209, height: 232, layers: [
        .init(part: .earLeft, asset: "reference-norwegian-warm-ear-left",
          pivotX: 90.0, pivotY: 68.0,
          frame: .init(x: 0, y: 0, width: 209, height: 232)),
        .init(part: .earRight, asset: "reference-norwegian-warm-ear-right",
          pivotX: 184.0, pivotY: 72.0,
          frame: .init(x: 0, y: 0, width: 209, height: 232)),
        .init(part: .mane, asset: "reference-norwegian-warm-mane",
          pivotX: 104.5, pivotY: 157,
          frame: .init(x: 0, y: 0, width: 209, height: 232)),
        .init(part: .body, asset: "reference-norwegian-warm-body",
          pivotX: 104.5, pivotY: 116.0,
          frame: .init(x: 0, y: 0, width: 209, height: 232)),
        .init(part: .eyeLeft, asset: "reference-norwegian-warm-eye-left",
          pivotX: 78.5, pivotY: 108.0,
          frame: .init(x: 57, y: 87, width: 43, height: 42)),
        .init(part: .irisLeft, asset: "reference-norwegian-warm-iris-left",
          pivotX: 78.5, pivotY: 108.0,
          frame: .init(x: 57, y: 87, width: 43, height: 42)),
        .init(part: .eyeRight, asset: "reference-norwegian-warm-eye-right",
          pivotX: 138.0, pivotY: 107.5,
          frame: .init(x: 116, y: 86, width: 44, height: 43)),
        .init(part: .irisRight, asset: "reference-norwegian-warm-iris-right",
          pivotX: 138.0, pivotY: 107.5,
          frame: .init(x: 116, y: 86, width: 44, height: 43)),
        .init(part: .nose, asset: "reference-norwegian-warm-nose",
          pivotX: 108.5, pivotY: 131.5,
          frame: .init(x: 97, y: 124, width: 23, height: 15)),
        .init(part: .mouth, asset: "reference-norwegian-warm-mouth",
          pivotX: 108.5, pivotY: 146.0,
          frame: .init(x: 91, y: 137, width: 35, height: 18)),
      ])
    case .norwegianSilver:
      return .init(id: id, width: 219, height: 232, layers: [
        .init(part: .earLeft, asset: "reference-norwegian-silver-ear-left",
          pivotX: 92.5, pivotY: 70.0,
          frame: .init(x: 0, y: 0, width: 219, height: 232)),
        .init(part: .earRight, asset: "reference-norwegian-silver-ear-right",
          pivotX: 191.5, pivotY: 74.0,
          frame: .init(x: 0, y: 0, width: 219, height: 232)),
        .init(part: .mane, asset: "reference-norwegian-silver-mane",
          pivotX: 109.5, pivotY: 156,
          frame: .init(x: 0, y: 0, width: 219, height: 232)),
        .init(part: .body, asset: "reference-norwegian-silver-body",
          pivotX: 109.5, pivotY: 116.0,
          frame: .init(x: 0, y: 0, width: 219, height: 232)),
        .init(part: .eyeLeft, asset: "reference-norwegian-silver-eye-left",
          pivotX: 80.0, pivotY: 105.5,
          frame: .init(x: 57, y: 84, width: 46, height: 43)),
        .init(part: .irisLeft, asset: "reference-norwegian-silver-iris-left",
          pivotX: 80.0, pivotY: 105.5,
          frame: .init(x: 57, y: 84, width: 46, height: 43)),
        .init(part: .eyeRight, asset: "reference-norwegian-silver-eye-right",
          pivotX: 140.5, pivotY: 104.5,
          frame: .init(x: 117, y: 83, width: 47, height: 43)),
        .init(part: .irisRight, asset: "reference-norwegian-silver-iris-right",
          pivotX: 140.5, pivotY: 104.5,
          frame: .init(x: 117, y: 83, width: 47, height: 43)),
        .init(part: .nose, asset: "reference-norwegian-silver-nose",
          pivotX: 110.5, pivotY: 129.0,
          frame: .init(x: 99, y: 121, width: 23, height: 16)),
        .init(part: .mouth, asset: "reference-norwegian-silver-mouth",
          pivotX: 111.5, pivotY: 144.5,
          frame: .init(x: 94, y: 135, width: 35, height: 19)),
      ])
    case .norwegianCream:
      return .init(id: id, width: 220, height: 232, layers: [
        .init(part: .earLeft, asset: "reference-norwegian-cream-ear-left",
          pivotX: 94.0, pivotY: 72.0,
          frame: .init(x: 0, y: 0, width: 220, height: 232)),
        .init(part: .earRight, asset: "reference-norwegian-cream-ear-right",
          pivotX: 191.5, pivotY: 73.0,
          frame: .init(x: 0, y: 0, width: 220, height: 232)),
        .init(part: .mane, asset: "reference-norwegian-cream-mane",
          pivotX: 110.0, pivotY: 156,
          frame: .init(x: 0, y: 0, width: 220, height: 232)),
        .init(part: .body, asset: "reference-norwegian-cream-body",
          pivotX: 110.0, pivotY: 116.0,
          frame: .init(x: 0, y: 0, width: 220, height: 232)),
        .init(part: .eyeLeft, asset: "reference-norwegian-cream-eye-left",
          pivotX: 81.5, pivotY: 106.5,
          frame: .init(x: 58, y: 85, width: 47, height: 43)),
        .init(part: .irisLeft, asset: "reference-norwegian-cream-iris-left",
          pivotX: 81.5, pivotY: 106.5,
          frame: .init(x: 58, y: 85, width: 47, height: 43)),
        .init(part: .eyeRight, asset: "reference-norwegian-cream-eye-right",
          pivotX: 142.5, pivotY: 106.5,
          frame: .init(x: 119, y: 85, width: 47, height: 43)),
        .init(part: .irisRight, asset: "reference-norwegian-cream-iris-right",
          pivotX: 142.5, pivotY: 106.5,
          frame: .init(x: 119, y: 85, width: 47, height: 43)),
        .init(part: .nose, asset: "reference-norwegian-cream-nose",
          pivotX: 112.5, pivotY: 130.0,
          frame: .init(x: 101, y: 122, width: 23, height: 16)),
        .init(part: .mouth, asset: "reference-norwegian-cream-mouth",
          pivotX: 113.5, pivotY: 145.0,
          frame: .init(x: 96, y: 136, width: 35, height: 18)),
      ])
    case .norwegianHero:
      return .init(id: id, width: 431, height: 373, layers: [
        .init(part: .earLeft, asset: "reference-norwegian-hero-ear-left",
          pivotX: 175.0, pivotY: 127.0,
          frame: .init(x: 0, y: 0, width: 431, height: 373)),
        .init(part: .earRight, asset: "reference-norwegian-hero-ear-right",
          pivotX: 360.0, pivotY: 131.0,
          frame: .init(x: 0, y: 0, width: 431, height: 373)),
        .init(part: .mane, asset: "reference-norwegian-hero-mane",
          pivotX: 215.5, pivotY: 279,
          frame: .init(x: 0, y: 0, width: 431, height: 373)),
        .init(part: .body, asset: "reference-norwegian-hero-body",
          pivotX: 215.5, pivotY: 186.5,
          frame: .init(x: 0, y: 0, width: 431, height: 373)),
        .init(part: .eyeLeft, asset: "reference-norwegian-hero-eye-left",
          pivotX: 164.0, pivotY: 179.0,
          frame: .init(x: 128, y: 144, width: 72, height: 70)),
        .init(part: .irisLeft, asset: "reference-norwegian-hero-iris-left",
          pivotX: 164.0, pivotY: 179.0,
          frame: .init(x: 128, y: 144, width: 72, height: 70)),
        .init(part: .eyeRight, asset: "reference-norwegian-hero-eye-right",
          pivotX: 272.0, pivotY: 174.0,
          frame: .init(x: 235, y: 139, width: 74, height: 70)),
        .init(part: .irisRight, asset: "reference-norwegian-hero-iris-right",
          pivotX: 272.0, pivotY: 174.0,
          frame: .init(x: 235, y: 139, width: 74, height: 70)),
        .init(part: .nose, asset: "reference-norwegian-hero-nose",
          pivotX: 220.0, pivotY: 214.5,
          frame: .init(x: 202, y: 203, width: 36, height: 23)),
        .init(part: .mouth, asset: "reference-norwegian-hero-mouth",
          pivotX: 220.0, pivotY: 239.0,
          frame: .init(x: 190, y: 224, width: 60, height: 30)),
      ])
    }
  }
}
