import Foundation

/// Authored appearances from the supplied reference. These values own presentation, never state.
public enum CharacterMascotVariant: String, CaseIterable, Codable, Sendable {
  case hero, white, black, arcade
}

public enum CharacterNorwegianVariant: String, CaseIterable, Codable, Sendable {
  case hero, warmTabby, silver, creamBrown
}

public enum CharacterBodyMaterial: String, CaseIterable, Codable, Sendable {
  case original, black, white, graphite
}

public enum CharacterMetalMaterial: String, CaseIterable, Codable, Sendable {
  case original, silver, sand, black
}

public enum CharacterCushionMaterial: String, CaseIterable, Codable, Sendable {
  case original, black, gray, ivory, cream
}

public enum CharacterLightMaterial: String, CaseIterable, Codable, Sendable {
  case original, cyan, purple, pink, orange, green
}

public struct CharacterHeadsetMaterials: Sendable, Equatable, Codable {
  public let shell: CharacterBodyMaterial
  public let metal: CharacterMetalMaterial
  public let cushions: CharacterCushionMaterial
  public let light: CharacterLightMaterial

  public init(
    shell: CharacterBodyMaterial = .original, metal: CharacterMetalMaterial = .original,
    cushions: CharacterCushionMaterial = .original, light: CharacterLightMaterial = .original
  ) {
    self.shell = shell
    self.metal = metal
    self.cushions = cushions
    self.light = light
  }

  public static let original = Self()
}

/// `headset: nil` selects the authored headset-free illustration; the selected worn variant is
/// retained for reattachment. This avoids inventing pixels hidden behind hardware.
/// `headsetFree` selects that same illustration directly.
/// A cat cannot carry mascot material settings or a headset.
public enum CharacterReferenceAppearance: Sendable, Equatable, Codable {
  case mascot(
    variant: CharacterMascotVariant, body: CharacterBodyMaterial = .original,
    headset: CharacterHeadsetMaterials? = .original)
  case headsetFree(body: CharacterBodyMaterial = .original)
  case norwegianForest(CharacterNorwegianVariant)

  public var artDirection: CharacterArtDirection { .reference(self) }
  public var nativeWidth: Int { Int(rig.width) }
  public var nativeHeight: Int { Int(rig.height) }

  var isCat: Bool {
    if case .norwegianForest = self { return true }
    return false
  }

  var artworkID: CharacterReferenceArtworkID {
    switch self {
    case .mascot(_, _, nil): .mascotBare
    case .mascot(let variant, _, .some):
      switch variant {
      case .hero: .mascotHero
      case .white: .mascotWhite
      case .black: .mascotBlack
      case .arcade: .mascotArcade
      }
    case .headsetFree: .mascotBare
    case .norwegianForest(let variant):
      switch variant {
      case .hero: .norwegianHero
      case .warmTabby: .norwegianWarm
      case .silver: .norwegianSilver
      case .creamBrown: .norwegianCream
      }
    }
  }

  var rig: CharacterReferenceRig { CharacterReferenceCatalog.rig(artworkID) }

  func asset(for layer: CharacterReferenceRig.Layer) -> CharacterImageAsset? {
    var suffix = "original"
    switch self {
    case .mascot(_, let body, let headset):
      switch layer.part {
      case .body, .eyeLeft, .eyeRight, .mouth: suffix = body.rawValue
      case .headsetShell:
        guard let headset else { return nil }
        suffix = headset.shell.rawValue
      case .headsetMetal:
        guard let headset else { return nil }
        suffix = headset.metal.rawValue
      case .headsetCushions:
        guard let headset else { return nil }
        suffix = headset.cushions.rawValue
      case .headsetLight:
        guard let headset else { return nil }
        suffix = headset.light.rawValue
      default: break
      }
    case .headsetFree(let body):
      if [.body, .eyeLeft, .eyeRight, .mouth].contains(layer.part) { suffix = body.rawValue }
    case .norwegianForest: break
    }
    // The resource catalog is authoritative. Do not synthesize resource names that are not
    // generated by the reference asset pipeline.
    return .init(
      uncheckedName: suffix == "original" ? layer.asset : "\(layer.asset)-\(suffix)",
      source: .package)
  }

  // A small, explicit interchange contract. Unknown kinds, extra/incompatible fields and missing
  // fields are failures; importing never coerces an invalid selection to a default appearance.
  private enum Key: String, CodingKey { case kind, variant, body, headset }
  private enum Kind: String, Codable { case mascot, headsetFree, norwegianForest }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: Key.self)
    let kind = try container.decode(Kind.self, forKey: .kind)
    switch kind {
    case .mascot:
      try CharacterReferenceDocument.requireKeys(
        ["kind", "variant", "body", "headset"], decoder: decoder)
      // Explicit null denotes a removed headset; an absent field is not equivalent.
      guard container.contains(.headset) else {
        throw DecodingError.keyNotFound(Key.headset, .init(codingPath: decoder.codingPath,
          debugDescription: "headset must be an object or explicit null"))
      }
      self = .mascot(
        variant: try container.decode(CharacterMascotVariant.self, forKey: .variant),
        body: try container.decode(CharacterBodyMaterial.self, forKey: .body),
        headset: try container.decodeIfPresent(CharacterHeadsetMaterials.self, forKey: .headset))
    case .headsetFree:
      try CharacterReferenceDocument.requireKeys(["kind", "body"], decoder: decoder)
      self = .headsetFree(body: try container.decode(CharacterBodyMaterial.self, forKey: .body))
    case .norwegianForest:
      try CharacterReferenceDocument.requireKeys(["kind", "variant"], decoder: decoder)
      self = .norwegianForest(try container.decode(CharacterNorwegianVariant.self, forKey: .variant))
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: Key.self)
    switch self {
    case .mascot(let variant, let body, let headset):
      try container.encode(Kind.mascot, forKey: .kind)
      try container.encode(variant, forKey: .variant)
      try container.encode(body, forKey: .body)
      try container.encode(headset, forKey: .headset)
    case .headsetFree(let body):
      try container.encode(Kind.headsetFree, forKey: .kind)
      try container.encode(body, forKey: .body)
    case .norwegianForest(let variant):
      try container.encode(Kind.norwegianForest, forKey: .kind)
      try container.encode(variant, forKey: .variant)
    }
  }
}

extension CharacterHeadsetMaterials {
  private enum Key: String, CodingKey { case shell, metal, cushions, light }

  public init(from decoder: any Decoder) throws {
    try CharacterReferenceDocument.requireKeys(["shell", "metal", "cushions", "light"], decoder: decoder)
    let c = try decoder.container(keyedBy: Key.self)
    self.init(
      shell: try c.decode(CharacterBodyMaterial.self, forKey: .shell),
      metal: try c.decode(CharacterMetalMaterial.self, forKey: .metal),
      cushions: try c.decode(CharacterCushionMaterial.self, forKey: .cushions),
      light: try c.decode(CharacterLightMaterial.self, forKey: .light))
  }
}
